### PR TITLE
replace netpbm with pnmio

### LINKED ISSUE #5: Please replace netpbm with another library
Netpbm is old and it is very hard to package. It has [no clear license](https://fedoraproject.org/wiki/LicenseAuditRecords) and nobody uses it anyway.

### PR DESCRIPTION
**Pull request by 183amir**
Fix #5.

### CODE REVIEW

**Comment by siebenkopf** [comment]
The error that you get is related to a memory issue, where you typically 
either free the same memory structure twice, or you write into memory 
locations, where you are not supposed to write to.

Implementing more complicated file IO in C/C++, you need to work on your 
C++. Additionally, you need to completely understand the Python C-API, 
particularly the reference counting there, to assure that you are not 
freeing memory twice (as it seems to happen) or, even worse because more 
difficult to detect, don't free memory at all.

I would recommend to compile and test your code in debug mode, 
eventually using a debugger. Try to run your tests with ./bin/gdb-python 
(which might yet be another thing to learn) ;-)

Enjoy!
Manuel

**Comment by 183amir** [comment]
Ok seems good to be merged IMO.

**Comment by siebenkopf** [comment]
Hey guys, why am I getting emails from coveralls? Did anyone set up a web hook or something similar to enable that?

**Comment by 183amir** [comment]
Coveralls is commenting on my pul request. I don't know why either. Maybe
because coverage increased a lot.

**Comment by anjos** [comment]
There is an e-mail that is sent to all package maintainers (people that have committed code I guess), when coverage increases or reduces. This one is for an increase, so the better! ;-)

**Pull request merged**
